evaluation_setup:
  selected_apis:
    - demo-model-a
    - demo-model-b

  paths:
    root_dir: "./infer_results"
    gt_dir: "./Ancient_Bench"
    result_folder: "evaluate_results"

  selected_data_category:
    - oracle_bone_artifacts
    - bronze_rubbings
    - bamboo_wooden_slips
    - silk_manuscripts
    - seals
    - inscription_rubbings
    - cliff_carvings
    - traditional_chinese_book_editions
    - calligraphys

verifier_params:
  ignore_st: false       # 是否忽略中文简繁体差异
  ignore_punc: true     # 是否忽略中英文标点符号
  ignore_space: true    # 是否忽略空白符号（含空格、换行等）
  ignore_case: false     # 是否忽略英文大小写